### ISSUE TITLE
Whitelisted services should be derived from corresponding timers 

### ISSUE THREAD

**Issue by george-angel** [Financial-Times/coco-fleet-unit-healthcheck#4]
~~The list of whitelisted services should be read from etcd on start up (or bonus star if you check etcd during runtime for the list) and services that want to be whitelisted should register themselves in etcd.~~

Edit: Better solution suggested by @tamas-molnar to dervice the list of whitelisted services by the fact they have a corresponding timer associated with them.

**Comment by tamas-molnar** [comment]
The information about whether a service has a timer is already there - if a foo.service  has a corresponding foo.timer, then can't the healthckeck app just figure it out on it's own? I assume it has the list of services and  timers.

**Comment by george-angel** [comment]
Yeah, that makes sense, probably even better as a solution
